config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :directors, only: [:index, :show]

  resources :works, only: [:index, :show] do
    get 'higher' => 'works#move_higher', as: 'higher', on: :member
  end

  resources :genres, only: [:show]

  root to: 'works#index'
  # get 'home/index' => 'home#index'
  namespace :login do
    resources :works, except: [:index, :show]
    resources :directors, except: [:index, :show]
    resource :profile
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  mount_uploader :image, WorkImageUploader

  has_many :works

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :country, presence: true

  # scope :by_new, ->{ order(updated_at: :desc) }
  scope :by_alphabet, ->{ order(name: :asc) }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :work_genres, dependent: :destroy
  has_many :works, through: :work_genres
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :image, ProfileImageUploader

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  mount_uploader :image, WorkImageUploader

  belongs_to :director
  has_many :work_genres, dependent: :destroy
  has_many :genres, through: :work_genres

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :release, presence: true
  validates :starring, presence: true
  validates :explanation, presence: true

  scope :by_alphabet, ->{ order(title: :asc) }
  scope :by_position, ->{ order(position: :asc) }
  # scope :by_new, ->{ order(updated_at: :desc) }
  acts_as_list
end

app/models/work_genre.rb
class WorkGenre < ApplicationRecord
  belongs_to :work
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director,only: [:show,]
  def index
    @q = Director.by_alphabet.ransack(params[:q])
    @directors = @q.result(distinct: true).page(params[:page]).per(6)
  end

  def show

  end

  private

  def set_director
    @director = Director.find(params[:id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def show
    @genre = Genre.find(params[:id])
    @q = @genre.works.includes(:director).ransack(params[:q])
    @works = @q.result(distinct: true).by_position.page(params[:page]).per(6)
    render 'works/index'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/login/application_controller.rb
class Login::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/login/directors_controller.rb
class Login::DirectorsController < Login::ApplicationController
  before_action :set_director,only: [:edit, :update, :destroy]

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(director_params)
    if @director.save
      redirect_to directors_path, notice: "データを保存しました。"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @director.update(director_params)
      redirect_to directors_path, notice: "データを更新しました。"
    else
      render 'edit'
    end
  end

  def destroy
    @director.destroy
    redirect_to directors_path, notice: "データを削除しました。"
  end

  private

  def director_params
    params[:director].permit(
      :name,
      :country,
      :image,
      :image_cache,
      :remove_image,
    )
  end
  def set_director
    @director = Director.find(params[:id])
  end
end

app/controllers/login/profiles_controller.rb
class Login::ProfilesController < Login::ApplicationController
  before_action :set_profile, only: [:edit, :update]

  def edit
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to edit_login_profile_path, notice: 'Your profile has been successfully saved.'
    else
      render 'edit'
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_login_profile_path, notice: 'Your profile has been successfully saved.'
    else
      render 'edit'
    end
  end

  private

  def set_profile
    @profile = current_user.profile || current_user.build_profile
  end

  def profile_params
    params.require(:profile).permit(
      :first_name,
      :last_name,
      :description,
      :image,
      :image_cache,
      :remove_image,
    )
  end
end

app/controllers/login/works_controller.rb
class Login::WorksController < Login::ApplicationController
  before_action :set_work,only: [:edit, :update, :destroy]

  def new
    @work = Work.new
    @work.director_id = params[:director_id] if params[:director_id]
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to works_path, notice: "データを保存しました。"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @work.update(work_params)
      redirect_to works_path, notice: "データを更新しました。"
    else
      render 'edit'
    end
  end

  def destroy
    @work.destroy
    redirect_to works_path, notice: "データを削除しました。"
  end

  def move_higher
    Work.find(params[:id]).move_higher
    redirect_to :action => 'index'
  end

  private

  def work_params
    params[:work].permit(
      :title,
      :release,
      :starring,
      :explanation,
      :director_id,
      :image,
      :image_cache,
      :remove_image,
      genre_ids: []
    )
  end
  def set_work
    @work = Work.find(params[:id])
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work,only: [:show]
  def index
    @q = Work.includes(:director).by_position.ransack(params[:q])
    @works = @q.result(distinct: true).page(params[:page]).per(6)
  end

  def show

  end


  def move_higher
    Work.find(params[:id]).move_higher
    redirect_to :action => 'index'
  end

  private

  def set_work
    @work = Work.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.haml
/ ======= Footer =======
%footer.footer{:role => "contentinfo"}
  .container
    .row
      .col-sm-6
        %p.mb-1 © Copyright MyPortfolio. All Rights Reserved
        .credits
          /
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=MyPortfolio
          Designed by
          %a{:href => "https://bootstrapmade.com/"} BootstrapMade
      .col-sm-6.social.text-md-right
        %a{:href => "#"}
          %span.icofont-twitter
        %a{:href => "#"}
          %span.icofont-facebook
%a.back-to-top{:href => "#"}
  %i.icofont-simple-up

app/views/application/_header.html.haml
#main-navbar.collapse.navbar-collapse.custom-navmenu
  .container.py-2.py-md-5
    .row.align-items-start
      .col-md-6
        %ul.custom-menu
          %li.active
            =link_to "Movies", works_path
          %li
            =link_to "Directors", directors_path
          -if user_signed_in?
            %li
              = link_to 'Edit Profile', edit_login_profile_path
            %li
              =link_to "Sign Out", destroy_user_session_path

          -else
            %li
              =link_to "Sign In", new_user_session_path
            %li
              =link_to "Sign Up", new_user_registration_path

      -if user_signed_in? && current_user.profile.present?
        .col-md-6.d-flex.flex-column
          =image_tag current_user.profile.image_url(:thumb) if current_user.profile.image.present?
          %h4.mt-2="#{current_user.profile.first_name} #{current_user.profile.last_name}"
          %p=current_user.profile.description

%nav.navbar.navbar-light.custom-navbar
  .container
    -# %a.navbar-brand{:href => "/works"} Movie Log
    =link_to "Movie Log", works_path, class: 'navbar-brand'
    %a.burger{"data-target" => "#main-navbar", "data-toggle" => "collapse", :href => "#"}
      %span

app/views/directors/_form.html.haml
=bootstrap_form_with model: @director, local: true do |f|
  =f.text_field :name
  =f.text_field :country
  =f.file_field :image
  =f.hidden_field :image_cache
  -if @director.image?
    .m-t-5
      =image_tag @director.image_url(:thumb)
      .checkbox.checkbox-primary.m-t-5
        =f.check_box_without_bootstrap :remove_image
        =f.label :remove_image, 'Image Delete'
  =f.submit

app/views/directors/index.html.haml
-# %h1 Movie Log
-# %p おすすめの映画を紹介しています
-#
-# - @directors.each_with_index do |director, index|
-#   #{index + 1}.
-#   =link_to director.name, director_path(director)
-#   %br
-# %hr
-# =link_to "新しい監督を登録", new_director_path




%main#main
  / ======= Directors Section =======
  %section.section.site-portfolio
    .container
      .row.mb-5.align-items-center
        .col-md-12.col-lg-6.mb-4.mb-lg-0{"data-aos" => "fade-up"}
          %h2 List of Directors
          %p.mb-0
          .search_form
            = search_form_for @q do |f|
              = f.label :title, "Keyword"
              = f.search_field :name_cont
              = f.submit "search"
        .col-md-12.col-lg-6.text-left.text-lg-right{"data-aos" => "fade-up", "data-aos-delay" => "100"}
          #filters.filters
            -# %a.active{"data-filter" => "*", :href => "#"} ALL
            -# %a{"data-filter" => ".web", :href => "#"} ACTION
            -# %a{"data-filter" => ".design", :href => "#"} ROMANCE
            -# %a{"data-filter" => ".branding", :href => "#"} DRAMA
            -# %a{"data-filter" => ".photography", :href => "#"} ANIME
      #portfolio-grid.row.no-gutter{"data-aos" => "fade-up", "data-aos-delay" => "200"}
        -@directors.each_with_index do |director, index|
          .item.web.col-sm-6.col-md-4.col-lg-4.mb-4
            -# %a.item-wrap.fancybox{:href => "director-single.html"}
            =link_to director_path(director), class: 'item-wrap fancybox' do
              .work-info
                %h3=director.name
                %span=director.country
              -# %img.img-fluid{:src => "/img/img_1.jpg"}/
              -if director.image.present?
                =image_tag director.image_url(:thumb), class: 'img-fluid'
              -else
                =image_tag '/img/default_image.png',class: 'img-fluid'
      =paginate @directors
      -if user_signed_in?
        =link_to new_login_director_path do
          %button.btn.btn-outline-info{:type => "button"} Add new director
      -# =link_to "新しい映画を登録", new_director_path

app/views/directors/show.html.haml
-# Director Name：#{@director.name}
-# %br
-# Country：#{@director.country}
-# %br
-# Works:
-# %br
-# - @director.works.each_with_index do |work, index|
-#   #{index + 1}.
-#   =link_to "#{work.title} (#{work.release})", work_path(work)
-#   %br
-# %hr
-# =link_to "一覧に戻る", directors_path
-# %br
-# =link_to "登録内容を編集する", edit_director_path(@director)
-# %br
-# =link_to "削除する", director_path(@director), method: :delete, data: {confirm: "削除しますか？"}
-# %br
-# =link_to 'Add new movie', new_work_path(director_id: @director.id)














%main#main
  %section.section
    .container
      .row.mb-4.align-items-center
        .col-md-6{"data-aos" => "fade-up"}
          %h2=@director.name
          %p=@director.country
      .container
        .row.align-items-stretch
          .col-md-8{"data-aos" => "fade-up"}
            -# %img.img-fluid{:alt => "Image", :src => "/img/img_1_big.jpg"}/
            -if @director.image.present?
              =image_tag  @director.image_url, alt: @director.name, class:'img-fluid'
            -else
              =image_tag '/img/default_image.png', class:'img-fluid'
          .col-md-3.ml-auto{"data-aos" => "fade-up", "data-aos-delay" => "100"}
            .sticky-content
              -# %h3.h3
              -#   =link_to @work.director.name, director_path(@work.director)
              -# %p.mb-4
              -#   %span.text-muted=@work.director.country
              -# %p.mb-4
              -#   %span.text-muted=@work.starring
              -# .mb-5
              -#   %p
              -#     =@work.explanation
              %h4.h4.mb-3 WORKS
              %ul.list-unstyled.list-line.mb-5
                - @director.works.each do |work|
                  %li
                    =link_to "#{work.title} (#{work.release})", work_path(work)
        %hr
      =link_to directors_path, class:"btn" do
        %button.btn.btn-outline-secondary{:type => "button"} > Back
      -if user_signed_in?
        =link_to edit_login_director_path(@director), class:"btn" do
          %button.btn.btn-outline-warning{:type => "button"} Edit
        =link_to new_login_work_path(director_id: @director.id), class:"btn" do
          %button.btn.btn-outline-info{:type => "button"} Add New Movie
        =link_to login_director_path(@director), method: :delete, data: {confirm: "削除しますか？"}, class:"btn" do
          %button.btn.btn-outline-dark{:type => "button"} Delete

app/views/home/index.html.haml
ホームです

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Movielog
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "keywords"}/
    = csrf_meta_tags
    = csp_meta_tag
    / Favicons
    %link{:href => "/img/favicon.png", :rel => "icon"}/
    %link{:href => "/img/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    / Google Fonts
    %link{:href => "https://fonts.googleapis.com/css?family=https://fonts.googleapis.com/css?family=Inconsolata:400,500,600,700|Raleway:400,400i,500,500i,600,600i,700,700i", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "header"
    -if notice.present?
      .container
        %p.notice.alert.alert-success{:role => "alert"}
          =notice
    -if alert.present?
      .container
        %p.alert.alert-danger{:role => "alert"}
          =alert
    -# = notice if notice
    -# -if notice
    -#   = notice
    = yield
    = render "footer"
    = javascript_include_tag "application"

app/views/login/directors/_form.html.haml
=bootstrap_form_with model: [:login, @director], local: true do |f|
  =f.text_field :name
  =f.text_field :country
  =f.file_field :image
  =f.hidden_field :image_cache
  -if @director.image?
    .m-t-5
      =image_tag @director.image_url(:thumb)
      .checkbox.checkbox-primary.m-t-5
        =f.check_box_without_bootstrap :remove_image
        =f.label :remove_image, 'Image Delete'
  =f.submit

app/views/login/directors/edit.html.haml
.container.pt-3.pb-3
  %h2 EDIT
  =render 'form'
  %hr
  -# =link_to "詳細ページへ戻る", director_path(@director)
  =link_to director_path(@director) do
    %button.btn.btn-outline-secondary{:type => "button"} > Back

app/views/login/directors/new.html.haml
.container.pt-3.pb-3
  %h2 Add New director
  =render 'form'
  %hr
    =link_to directors_path do
      %button.btn.btn-outline-secondary{:type => "button"} > Back to List

app/views/login/profiles/edit.html.haml
%main#main
  .site-section.pb-0.site-portfolio
    .container
      .row.mb-5.align-items-end
        .col-md-12{"data-aos" => "fade-up"}
          %h2 Profile
          %p.mb-0
            Introduce yourself and let's introduce great movies with us!
      .row
        .col-md-12.mb-5.mb-md-0{"data-aos" => "fade-up"}
          =bootstrap_form_with model: [:login, @profile], url: login_profile_path, local: true do |f|
            .row
              .col-md-6
                =f.text_field :first_name
              .col-md-6
                =f.text_field :last_name
              .col-md-12
                =f.text_area :description
              .col-md-12.mb-3
                =f.file_field :image
                =f.hidden_field :image_cache
                -if @profile.image?
                  .js-image-preview.m-t-5
                    =image_tag @profile.image_url(:thumb)
                    .checkbox.checkbox-primary.m-t-5
                      =f.check_box_without_bootstrap :remove_image
                      =f.label :remove_image, 'Image Delete'
              =f.submit 'Save profile', class: "readmore d-block w-100"

app/views/login/works/_form.html.haml
=bootstrap_form_with model: [:login, @work], local: true do |f|
  =f.text_field :title
  =f.collection_select :director_id, Director.all, :id, :name, include_blank: true, class: 'form-control '
  =f.collection_check_boxes :genre_ids, Genre.all, :id, :name, class: 'form-contral'
  =f.text_field :release
  =f.text_field :starring
  =f.text_area :explanation
  =f.file_field :image
  =f.hidden_field :image_cache
  -if @work.image?
    .m-t-5
      =image_tag @work.image_url(:thumb)
      .checkbox.checkbox-primary.m-t-5
        =f.check_box_without_bootstrap :remove_image
        =f.label :remove_image, 'Image Delete'
  =f.submit

app/views/login/works/edit.html.haml
.container.pt-3.pb-3
  %h2 EDIT
  =render 'form'
  %hr
  -# =link_to "> Back", work_path(@work)
  =link_to work_path(@work) do
    %button.btn.btn-outline-secondary{:type => "button"} > Back
  -# <button type="button" class="btn btn-outline-secondary">Secondary</button>

app/views/login/works/new.html.haml
.container.pt-3.pb-3
  %h2 Add New Movie
  =render 'form'
  %hr
    =link_to works_path do
      %button.btn.btn-outline-secondary{:type => "button"} > Back to List

app/views/works/_form.html.haml
=bootstrap_form_with model: @work, local: true do |f|
  =f.text_field :title
  =f.collection_select :director_id, Director.all, :id, :name, include_blank: true, class: 'form-control '
  =f.text_field :release
  =f.text_field :starring
  =f.text_area :explanation
  =f.file_field :image
  =f.hidden_field :image_cache
  -if @work.image?
    .m-t-5
      =image_tag @work.image_url(:thumb)
      .checkbox.checkbox-primary.m-t-5
        =f.check_box_without_bootstrap :remove_image
        =f.label :remove_image, 'Image Delete'
  =f.submit

app/views/works/index.html.haml
-# %h1 Movie Log
-# %p おすすめの映画を紹介しています
-#
-# - @works.each_with_index do |work, index|
-#   #{index + 1}.
-#   =link_to work.title, work_path(work)
-#   %br
-# %hr
-# =link_to "新しい映画を登録", new_work_path


/ ======= Navbar =======

%main#main
  / ======= Works Section =======
  %section.section.site-portfolio
    .container
      .row.mb-5.align-items-center
        .col-md-12.col-lg-6.mb-4.mb-lg-0{"data-aos" => "fade-up"}
          %h2 List of Films
          %p.mb-0 Let us find your favorite movie!
          .search_form
            = search_form_for @q do |f|
              = f.label :title, "Keyword"
              = f.search_field :title_cont
              = f.submit "search"
        .col-md-12.col-lg-6.text-left.text-lg-right{"data-aos" => "fade-up", "data-aos-delay" => "100"}
          -# #filters.filters
          =link_to "ALL", works_path
          -Genre.all.each do |genre|
            =link_to genre.name.upcase, genre_path(genre)

      #portfolio-grid.row.no-gutter{"data-aos" => "fade-up", "data-aos-delay" => "200"}
        -@works.each_with_index do |work, index|
          .item.web.col-sm-6.col-md-4.col-lg-4.mb-4
            -# %a.item-wrap.fancybox{:href => "work-single.html"}
            =link_to work_path(work), class: 'item-wrap fancybox' do
              .work-info
                %h3=work.title
                %span=work.release
                %br
                %span=work.director.name
              -# %img.img-fluid{:src => "/img/img_1.jpg"}/
              -if work.image.present?
                =image_tag work.image_url(:thumb), class: 'img-fluid'
              -else
                =image_tag '/img/default_image.png',class: 'img-fluid'
            = link_to higher_work_path(work), class: work.first? ? 'disabled' : '' do
              %i.fa.fa-arrow-up
      =paginate @works
      -if user_signed_in?
        =link_to new_login_work_path do
          %button.btn.btn-outline-info{:type => "button"} Add new movie
      -# =link_to "新しい映画を登録", new_work_path

app/views/works/show.html.haml
-# Movie Title：#{@work.title}
-# %br
-# Release Date：#{@work.release}
-# %br
-# Starring：#{@work.starring}
-# %br
-# Director :
-# =link_to @work.director.name, director_path(@work.director)
-# -# - director = Director.find(@work.director_id)
-# -# Director :#{director.name}
-# %br
-#
-# -# - exit
-# - if @work.director.works.length > 1
-#   [Related Works]
-#   %br
-#   - index = 0
-#   - @work.director.works.each do |work|
-#     -if @work != work
-#       #{index + 1}.
-#       =link_to "#{work.title} (#{work.release})", work_path(work)
-#       %br
-#
-# Description :#{@work.explanation}
-# %hr
-# =link_to "一覧に戻る", works_path
-# %br
-# =link_to "登録内容を編集する", edit_work_path(@work)
-# %br
-# =link_to "削除する", work_path(@work), method: :delete, data: {confirm: "削除しますか？"}


%main#main
  %section.section
    .container
      .row.mb-4.align-items-center
        .col-md-6{"data-aos" => "fade-up"}
          %h2=@work.title
          %p=@work.release
          -@work.genres.each do |genre|
            =link_to genre.name, genre_path(genre), class: "genre_tag"
      .container
        .row.align-items-stretch
          .col-md-8{"data-aos" => "fade-up"}
            -# %img.img-fluid{:alt => "Image", :src => "/img/img_1_big.jpg"}/
            -if @work.image.present?
              =image_tag  @work.image_url, alt: @work.title, class:'img-fluid'
            -else
              =image_tag '/img/default_image.png', class:'img-fluid'
          .col-md-3.ml-auto{"data-aos" => "fade-up", "data-aos-delay" => "100"}
            .sticky-content
              %h3.h3
                Director: #{link_to @work.director.name, director_path(@work.director)}
              %p.mb-4
                %span.text-muted=@work.director.country
              %p.mb-4
                %span.text-muted Starring: #{@work.starring}
              .mb-5
                %p
                  =@work.explanation
              %h4.h4.mb-3 RELATED WORKS
              %ul.list-unstyled.list-line.mb-5
                - @work.director.works.each do |work|
                  -if @work != work
                    %li
                      =link_to "#{work.title} (#{work.release})", work_path(work)
        %hr
      =link_to works_path, class:"btn" do
        %button.btn.btn-outline-secondary{:type => "button"} > Back
      -if user_signed_in?
        =link_to edit_login_work_path(@work), class:"btn" do
          %button.btn.btn-outline-warning{:type => "button"} Edit
        =link_to login_work_path(@work), method: :delete, data: {confirm: "削除しますか？"}, class:"btn" do
          %button.btn.btn-outline-dark{:type => "button"} Delete